#Reload conf by Ctrl + B, then write :source-file ~/.tmux.conf
#set-option -g default-shell "/bin/bash"

# Status
set -g message-style bg='#181819',fg='#181819'
set -g status-style bg='#181819',fg='#181819'
set -g status-interval 1
set -g status-position bottom

#removes number and time
set -g status-left ''
set -g status-right ''

set-window-option -g window-status-style fg='#ffdd33',bg=default
set-window-option -g window-status-current-style fg='#ffdd33',bg='#181819',bold

set -g pane-active-border-style bg=default,fg='#ffdd33'
set -g pane-border-style fg='#ffdd33'

set -g status-justify centre


# Status end

set -g prefix C-b
bind-key -n C-a send-prefix

set -g base-index 1
set -g renumber-windows on
set-option -g mouse on
set -g set-clipboard on
set -g history-limit 10000
set -sg escape-time 10
set -g focus-events on

#set -g default-terminal "xterm-256color"
#set -g terminal-overrides "xterm-256color"
#set -ga terminal-overrides ",xterm-256color:Tc"

set -g default-terminal "tmux-256color"
set -g terminal-features ',alacritty:RGB'
set -g terminal-overrides ',*:Tc'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0


# Keybinds

# Zoom
bind -r m resize-pane -Z

# Movement and resize vim controls
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

bind  k select-pane -U 
bind  j select-pane -D 
bind  h select-pane -L 
bind  l select-pane -R 

# Rebind splits
bind v split-window -h -c '#{pane_current_path}' -l '35%'
bind b split-window -v -c '#{pane_current_path}' -l '35%'

unbind Up     
unbind Down   
unbind Left   
unbind Right  

unbind C-Up   
unbind C-Down 
unbind C-Left 
unbind C-Right

# Rebind rename to R
bind-key r command-prompt -I "#W" "rename-window '%%'"


# Plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @continuum-restore 'on'

# {{{tmux-prefix-highlight
set -g @prefix_highlight_fg 'colour00'
set -g @prefix_highlight_bg 'red'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=colour00,bg=colour05,bold'
set -g @prefix_highlight_prefix_prompt 'PREFIX'
set -g @prefix_highlight_copy_prompt 'COPY'
# }}}


#set -g mouse on

# vim like copy and pate
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel xclip


set -g @catppuccin_status_justify "centre"
set -g @catppuccin_status_modules_right "directory meetings date_time"
set -g @catppuccin_status_modules_left "session window_name"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_pane_left_separator "█"
set -g @catppuccin_pane_right_separator "█"
set -g @catppuccin_pane_middle_separator "█"
set -g @catppuccin_date_time_text "%H:%M"
set -g @catppuccin_pane_active_border_style "fg=#ffdd33"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text_color "#181819"
set -g @catppuccin_window_number_color "#f0f0f0"
set -g @catppuccin_window_current_text_color "#181819"
set -g @catppuccin_window_current_number_color "#ffd333"
set -g @catppuccin_window_current_background "#ffdd33"

# Tmux package manager
run '~/.tmux/plugins/tpm/tpm'
